export enum CONTROL_TYPE {
  CHECKBOX = 'CHECKBOX',
  RADIO = 'RADIO',
  TEXTBOX = 'TEXTBOX',
  TOGGLE = 'TOGGLE',
  TEXTAREA = 'TEXTAREA',
  DROPDOWN = 'DROPDOWN',
  FORM_GROUP = 'FORM_GROUP',
  DATEPICKER = 'DATEPICKER',
  FORM_HINT = 'FORM_HINT',
  GIST = 'GIST',
  BUTTON = 'BUTTON',
}
