name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_BASE: ${{ github.event.pull_request.base.sha }}
  NX_HEAD: ${{ github.sha }}

jobs:
  main:
    name: Nx Cloud - Lint, test and build in parallel
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.0
    with:
      number-of-agents: 3
      parallel-commands: |
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected -t lint --parallel=3 & npx nx affected -t test --parallel=3 --configuration=ci & npx nx affected -t build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.0
    with:
      number-of-agents: 3
